/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommentDto {
  content?: string;
  createdAt: string;
  id?: string | null;
  messageId: string;
  parentId?: string | null;
  username?: string;
}
