/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommentDto } from "./comment-dto";

export interface MessageDto {
  content?: string;
  createAt: string;
  id?: string;
  username: string;
  comments?: CommentDto[];
}
