/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CommentDto } from './models/comment-dto';
export type { LoginDto } from './models/login-dto';
export type { MessageDto } from './models/message-dto';
export type { UserDto } from './models/user-dto';
