/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { MessageDto } from 'app/services/models';


export interface GetAllMessage$Params {
}
export interface ApiResponse {
  data: MessageDto[]; 
  message: string;
  status: number;
  success: boolean; 
}

export function getAllMessage(http: HttpClient, rootUrl: string, params?: GetAllMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllMessage.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponse>;  // Expecting an array of posts
    })
  );
}

getAllMessage.PATH = '/api/message';
