/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addComment } from '../fn/comment-controller/add-comment';
import { AddComment$Params } from '../fn/comment-controller/add-comment';
import { getCommentsTree } from '../fn/comment-controller/get-comments-tree';
import { GetCommentsTree$Params } from '../fn/comment-controller/get-comments-tree';

@Injectable({ providedIn: 'root' })
export class CommentControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `addComment()` */
  static readonly AddCommentPath = '/api/comment/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addComment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addComment$Response(params: AddComment$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return addComment(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addComment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addComment(params: AddComment$Params, context?: HttpContext): Observable<{
}> {
    return this.addComment$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getCommentsTree()` */
  static readonly GetCommentsTreePath = '/api/comment/{messageId}/load_comment';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCommentsTree()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCommentsTree$Response(params: GetCommentsTree$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return getCommentsTree(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCommentsTree$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCommentsTree(params: GetCommentsTree$Params, context?: HttpContext): Observable<{
}> {
    return this.getCommentsTree$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
